import './globals.css';

import { AuthSessionProvider } from '@/providers/auth-session-provider';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthSessionProvider session={session}>{children}</AuthSessionProvider>
            </body>
        </html>
    );
}
