import './globals.css';

import { AuthSessionProvider } from '@/providers/auth-session-provider';
import type { Metadata } from 'next';
import { Public_Sans } from 'next/font/google';
import { QueryProvider } from '@/providers/query-provider';
import { ToastProvider } from '@/providers/toast-provider';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';

const public_sans = Public_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={public_sans.className}>
                <AuthSessionProvider session={session}>
                    <ToastProvider />
                    <QueryProvider>{children}</QueryProvider>
                </AuthSessionProvider>
            </body>
        </html>
    );
}
