import './globals.css';

import { AuthSessionProvider } from '@/providers/auth-session-provider';
import type { Metadata } from 'next';
import { ModalProvider } from '@/providers/modal-provider';
import { Nunito } from 'next/font/google';
import { QueryProvider } from '@/providers/query-provider';
import { ToastProvider } from '@/providers/toast-provider';
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';

const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'KEMRI Boardroom',
    description: 'Generated by create next app',
    generator: 'Next.js',
    manifest: '/manifest.json',
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en">
            <body className={nunito.className}>
                <AuthSessionProvider session={session}>
                    <ToastProvider />
                    <QueryProvider>
                        <ModalProvider />
                        {children}
                    </QueryProvider>
                </AuthSessionProvider>
            </body>
        </html>
    );
}
